# Generated by Django 3.1.4 on 2020-12-20 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20201220_0203'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
